#!/usr/bin/env bash

# Script for creating symlinks under $HOME for any file in the current directory.
#
# (c) Arne Brasseur 2012-2023
#
# Use --dry-run to see what it would do without performing any actions.
#
# Generally this script is conservative, if an operation is destructive, for
# instance because there's already a file or other symlink in place, then it
# reports a warning and ignores that file.
#
# The only exception is if the file that's in the way is identical to the file
# being linked, in that case the file under $HOME gets replaced by a symlink.
#
# Run with `-f` to force updating files/symlinks that are in the way. The
# existing file will get renamed to have a `.bak` suffix.
#
# Files listed in the IGNORE file are ignored.

ARG="$1"

print_linking() {
    echo $'\e[34m[\e[33m⇠\e[34m]\e[0m' "$@"
}

print_forcing() {
    echo $'\e[34m[\e[31m⇠\e[34m]\e[0m' "$@"
}

print_already_linked() {
    echo $'\e[34m[\e[32m✓\e[34m]\e[0m' "$@"
}

print_problem() {
    echo $'\e[34m[\e[31m!\e[34m]\e[0m' "$@"
}

print_recursing() {
    echo $'  \e[34m[\e[33m⇣\e[34m]\e[0m' "$@"
}

dotdir() {
    cd `dirname "${BASH_SOURCE[0]}"` && echo "`pwd`/$1"
}

export IGNORE="$(cat "`dotdir`/IGNORE")"

ignore_p() {
  echo "$IGNORE" | while read f ; do
      if [[  "$1" =~ ^$f($|/) ]]; then
          exit 1
      fi
  done
  [[ $? -eq 1 ]] || false
}

export -f ignore_p

scan_files() {
    export path="$1"
    find "$path" \
         -exec bash -c 'for f; do f="${f#"$path"}" ; ignore_p "$f" || printf "$f\n"; done' \
         find-sh {} \;
}

do_rm() {
    if [[ "$ARG" = "--dry-run" ]]; then
        echo rm "$1"
    else
        rm "$1"
    fi
}

do_ln_s() {
    if [[ "$ARG" = "--dry-run" ]]; then
        echo ln -s "$1" "$2"
    else
        ln -s "$1" "$2"
    fi
}

create_symlink_if_possible() {
    local dotfile=$1

    if [[ -e "$HOME/$dotfile" ]]; then
        if cmp --silent -- "`dotdir $dotfile`" "$HOME/$dotfile"; then
            print_linking "$dotfile : identical file in the way, replacing with symlink"
            do_rm "$HOME/$dotfile"
            do_ln_s "`dotdir $dotfile`" "$HOME/$dotfile"
        else
            print_problem "$dotfile : can't create symlink, different file is in the way."
        fi
    else
        print_linking "$dotfile : creating symlink"
        do_ln_s "`dotdir $dotfile`" "$HOME/$dotfile"
    fi
}

check_existing_symlink() {
    local dotfile=$1
    local target=$(readlink -f $HOME/$dotfile)

    if [[ "$target" != "`dotdir $dotfile`" ]]; then
        print_problem "$dotfile : symlink points elsewhere -> $target"
    else
        print_already_linked "$dotfile"
    fi
}

force_symlink() {
    local dotfile=$1

    print_forcing "$dotfile : forcing new symlink"
    mv "$HOME/$dotfile" "$HOME/${dotfile}.bak"
    ln -s "`dotdir $dotfile`" "$HOME/$dotfile"
}

handle_dotfile() {
    local dotfile=$1

    if [[ -L "$HOME/$dotfile" ]]; then
        if [[ "$ARG" == "-f" ]]; then
            force_symlink $dotfile
        else
            check_existing_symlink $dotfile
        fi
    else
        create_symlink_if_possible $dotfile
    fi
}

handle_directory() {
    local dir=$1;
    mkdir -p "$HOME/$dir"
}

handle() {
    local dotfile=$1

    if [[ -f "${dotfile}" ]]; then
        handle_dotfile "${dotfile}"
    elif [[ -d "${dotfile}" ]]; then
        handle_directory "${dotfile}"
    fi
}

main() {
    for dotfile in $(scan_files `dotdir`) ; do
        if [[ ! "${dotfile}" = "" ]]; then
            handle "${dotfile}"
        fi
    done
}

main
