# packages:
# fcitx5 fcitx5-chinese-addons fcitx5-frontend-gtk3 fcitx5-frontend-qt5 fcitx5-config-qt fcitx5-rime

exec dbus-update-activation-environment --systemd \
    GTK_IM_MODULE \
    QT_IM_MODULE \
    XMODIFIERS \
    SDL_IM_MODULE \
    GLFW_IM_MODULE

set $export_fcitx export GTK_IM_MODULE=fcitx; export QT_IM_MODULE=fcitx; export XMODIFIERS=@im=fcitx; export SDL_IM_MODULE=fcitx; export GLFW_IM_MODULE=ibus
exec $export_fcitx

exec fcitx5 -d --replace
